//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17626
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tera {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class GamePlay : global::System.Configuration.ApplicationSettingsBase {
        
        private static GamePlay defaultInstance = ((GamePlay)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GamePlay())));
        
        public static GamePlay Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public short LevelCap {
            get {
                return ((short)(this["LevelCap"]));
            }
            set {
                this["LevelCap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ServerRates {
            get {
                return ((int)(this["ServerRates"]));
            }
            set {
                this["ServerRates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>MetaWind</string>
  <string>Alehandr</string>
  <string>yksirius</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Administrators {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Administrators"]));
            }
            set {
                this["Administrators"] = value;
            }
        }
    }
}
